[package]
name = "check"
version = "0.1.0"
authors = ["Paul Roberto Messina <paul.messina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
